import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('React controls hydrate without errors and support complete user journeys',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('/');
 const hero=page.locator('[data-widget=cutaway]');await hero.getByRole('button',{name:'Reset',exact:true}).click();await hero.getByRole('button',{name:'Next stage'}).click();await expect(hero.locator('.plane.active text')).toHaveText('Observe');await hero.getByRole('button',{name:'Reset',exact:true}).click();await expect(hero.locator('.plane.active')).toHaveCount(0);
 await page.locator('.stage-index button').nth(3).click();await expect(page.locator('.stage-details details').nth(3)).toHaveAttribute('open','');await page.locator('.stage-details details').nth(3).getByRole('button',{name:'Next',exact:true}).click();await expect(page.locator('.stage-details details').nth(4)).toHaveAttribute('open','');
 const router=page.locator('[data-widget=router]');await router.getByRole('button',{name:'Escalation',exact:true}).click();await router.getByRole('button',{name:'Next step'}).click();await expect(router.locator('h3')).toHaveText('Revisit the cluster evidence');await router.getByLabel('Inspect a designed skill route').selectOption('relational');await expect(router.locator('.route-output')).toContainText('GNN');
 const scan=page.locator('[data-widget=scan]');await scan.getByRole('button',{name:'Step',exact:true}).click();await expect(scan.locator('.timeline-row .now')).toHaveCount(3);await scan.getByLabel('Scenario').selectOption('intermittent');await expect(scan.locator('.timeline-row .now')).toHaveCount(0);
 await page.getByLabel('Inspect a failure scenario').selectOption('6');await expect(page.locator('.failure-row:visible')).toHaveCount(1);await expect(page.locator('.failure-row:visible')).toContainText('Interface failure');
 const review=page.locator('[data-widget=review]');await review.getByRole('button',{name:'Modify',exact:true}).click();await review.getByLabel('Reason for modification').fill('Need another observation');await review.getByRole('button',{name:'Apply illustrative change'}).click();await expect(review.locator('output')).toContainText('modified. Need another observation');await review.getByRole('button',{name:'Reset',exact:true}).click();await expect(review.locator('output')).toContainText('Awaiting');
 await page.locator('[data-widget=roles]').getByRole('button',{name:'Evaluator',exact:true}).click();await expect(page.locator('.role-panels article:visible')).toHaveCount(1);expect(errors).toEqual([]);
});
test('reduced motion disables playback while manual steps work',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');const hero=page.locator('[data-widget=cutaway]');await expect(hero.getByRole('button',{name:'Play the loop'})).toBeDisabled();await hero.getByRole('button',{name:'Next stage'}).click();await expect(hero.locator('.plane.active text')).toHaveText('Observe');expect(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior)).toBe('auto')});
test('finite playback pauses offscreen and does not resume automatically',async({page})=>{await page.goto('/');const hero=page.locator('[data-widget=cutaway]');await hero.getByRole('button',{name:'Reset',exact:true}).click();await hero.getByRole('button',{name:'Play the loop'}).click();await expect(hero.locator('.plane.active')).toHaveCount(1);await page.locator('#demo').scrollIntoViewIfNeeded();await expect(hero.getByRole('button',{name:/Resume loop|Replay loop/})).toBeAttached();const selected=await hero.locator('.plane.active text').textContent();await page.waitForTimeout(1050);expect(await hero.locator('.plane.active text').textContent()).toBe(selected);await hero.scrollIntoViewIfNeeded();await page.waitForTimeout(1050);expect(await hero.locator('.plane.active text').textContent()).toBe(selected)});
for(const route of ['/system/','/evidence/','/preview/'])test(`appendix accessibility ${route}`,async({page})=>{await page.goto(route);const {violations}=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(violations).toEqual([])});
test('real figures retain dimensions, natural colors and source links',async({page})=>{await page.goto('/evidence/');const figure=page.locator('figure').first(),img=figure.locator('img');await expect(img).toHaveAttribute('width',/\d+/);await expect(img).toHaveAttribute('height',/\d+/);expect(await img.evaluate(e=>({filter:getComputedStyle(e).filter,opacity:getComputedStyle(e).opacity}))).toEqual({filter:'none',opacity:'1'});await expect(figure.locator('figcaption a')).toHaveAttribute('href',/github.com.*9b985ca7/)});
