import {test,expect} from '@playwright/test';
import {SECTIONS} from '../src/lib/site';
test('skip link reaches main',async({page})=>{await page.goto('/');await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused()});
test('desktop chapter menu navigates beneath sticky header and tracks reading',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');
 for(const id of ['problem','built','why']){await page.locator('.chapter-menu>summary').click();await page.locator(`.chapter-menu a[href="/#${id}"]`).click();await expect(page.locator(`.chapter-menu a[href="/#${id}"]`)).toHaveAttribute('aria-current','location');const box=await page.locator(`#${id}`).boundingBox();expect(box!.y).toBeGreaterThanOrEqual(72);expect(box!.y).toBeLessThan(150);}
 await page.evaluate(()=>scrollTo(0,0));await expect(page.locator('.chapter-menu a[aria-current]')).toHaveCount(0);
});
test('mobile native disclosure closes on Escape and after navigation',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');const menu=page.locator('#menu');await menu.locator('summary').click();await expect(menu).toHaveAttribute('open','');await expect(menu.locator('[data-chapter-link]')).toHaveCount(8);await page.keyboard.press('Escape');await expect(menu).not.toHaveAttribute('open','');await expect(menu.locator('summary')).toBeFocused();await menu.locator('summary').click();await menu.getByRole('link',{name:/03 What we built/}).click();await expect(menu).not.toHaveAttribute('open','');await expect(page.locator('#built')).toBeInViewport();
});
test('appendix chapter links return to the homepage',async({page})=>{await page.goto('/evidence/');await page.locator('.chapter-menu>summary').click();await page.locator('.chapter-menu a[href="/#new"]').click();await expect(page).toHaveURL(/\/#new$/);await expect(page.locator('#new-h')).toBeVisible()});
test('JS off retains content and native mobile navigation',async({browser})=>{
 const context=await browser.newContext({javaScriptEnabled:false,reducedMotion:'reduce',viewport:{width:390,height:844}});const page=await context.newPage();await page.goto(test.info().project.use.baseURL as string);await page.locator('#menu>summary').click();await page.locator('#menu a[href="/#built"]').click();await expect(page.locator('#built')).toBeInViewport();expect(await page.locator('[data-section]').count()).toBe(SECTIONS.length);await page.locator('#how .disclosure').first().locator('summary').click();await expect(page.locator('#how .disclosure').first()).toHaveAttribute('open','');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await context.close();
});
for(const width of [390,768,1440])test(`all routes fit at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});for(const route of ['/','/system/','/evidence/','/preview/']){await page.goto(route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true)}});
