import type {ReactNode} from 'react';
import {Symbol} from './Symbol';
import L from '../lib/logo.generated.json';
import {STATUS,STATUS_IDS,type Status} from '../lib/status';
import {requireIssued,metric,cell,dataset,columnLabel,fmt,type Tagged} from '../lib/data';
import {FIGURES,type FigureId} from '../lib/figures';
import sizes from '../lib/media.generated.json';
import {mediaUrl} from '../lib/media';
import {REPO,SECTIONS} from '../lib/site';

export function Logo({variant='lockup'}:{variant?:'lockup'|'mark'|'wordmark'}){return <svg className={`logo logo--${variant}`} viewBox={L.viewBox[variant]} aria-hidden="true"><use href={variant==='wordmark'?'#lg-word':'#lg-mark'}/>{variant==='lockup'&&<use href="#lg-word"/>}</svg>}
export function LogoSprite(){return <svg width="0" height="0" style={{position:'absolute'}} aria-hidden="true"><defs><g id="lg-mark"><path className="lg-g" d={L.mark.green}/><path className="lg-k" d={L.mark.khaki}/></g><g id="lg-word"><path className="lg-g" d={L.wordmark.green}/><path className="lg-g" fillRule="evenodd" d={L.wordmark.holed}/><path className="lg-k" d={L.wordmark.khaki}/></g></defs></svg>}
const repo=`https://github.com/${REPO.slug}/tree/${REPO.commit}`;
const ChapterLinks=()=> <>{SECTIONS.map(s=><a key={s.id} href={`/#${s.id}`} data-chapter-link><span className="mono">{s.n}</span><span>{s.title}<small>{s.subtitle}</small></span></a>)}</>;
function ThemeToggle(){return <button className="theme-toggle" data-theme-toggle disabled aria-label="Switch to plum theme"><span className="theme-swatch" aria-hidden="true"/><span data-theme-label>Plum</span></button>}
export function Header(){return <header className="site-header"><div className="wrap site-header__inner"><a className="brand" href="/#top" aria-label="AVOLITE home"><Logo variant="mark"/><Logo variant="wordmark"/></a><nav className="site-nav" aria-label="Main navigation"><details className="chapter-menu"><summary>Story</summary><div className="chapter-links"><ChapterLinks/></div></details><a href="/system/">System</a><a href="/evidence/">Evidence</a><a href={repo}>Repository</a><ThemeToggle/></nav></div><details className="mobile-nav" id="menu"><summary>Menu</summary><nav className="chapter-links" aria-label="Mobile navigation"><ChapterLinks/><a className="aux-link" href="/system/">System</a><a className="aux-link" href="/evidence/">Evidence</a><a className="aux-link" href={repo}>Repository</a><ThemeToggle/></nav></details><span className="reading-progress" aria-hidden="true"/></header>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><a href="/#top" aria-label="AVOLITE home"><Logo/></a><nav className="footer-links" aria-label="Footer"><a href="/#problem">The story</a><a href="/system/">System</a><a href="/evidence/">Evidence</a><a href={repo}>Repository</a></nav></div><p className="footer-note">AVOLITE / SIH 2026 / PS 26055<br/>Radar DSP simulation evidence. Smart-scan architecture designed. Hardware validation pending.</p><p className="footer-note">Created by Sandesh Naik</p></div></footer>}
export function Tag({status}:{status:Status}){const entry=STATUS[status];return <span className={`tag tag--${status.toLowerCase()}`} data-status={status} style={{color:`var(${entry.token})`,borderStyle:entry.border}}><svg width="12" height="12" viewBox="0 0 12 12" aria-hidden="true" data-glyph={entry.glyph}>{status==='BUILT'?<rect x="2" y="2" width="8" height="8" fill="currentColor"/>:status==='ILLUSTRATIVE'?<path d="M1 9 9 1M3 11 11 3M1 4 4 1M8 11 11 8" stroke="currentColor"/>:<circle cx="6" cy="6" r="4" fill={status==='SIMULATED'?'currentColor':'none'} stroke="currentColor" strokeDasharray={status==='PLANNED'?'2 2':undefined}/>}</svg>{status}</span>}
export function Legend(){return <details className="disclosure"><summary>How to read the evidence labels</summary><dl className="legend">{STATUS_IDS.map(s=><div key={s}><dt><Tag status={s}/></dt><dd>{STATUS[s].definition}</dd></div>)}</dl></details>}
export function Section({id,headline,lede,theme='',children}:{id:typeof SECTIONS[number]['id'];headline:string;lede?:string;theme?:string;children:ReactNode}){return <section id={id} className={`chapter ${theme}`} data-section aria-labelledby={`${id}-h`}><div className="wrap"><header className="section-heading"><h2 id={`${id}-h`}>{headline}</h2>{lede&&<p className="lede">{lede}</p>}</header>{children}</div></section>}
export function Metric({tagged}:{tagged:Tagged}){const t=requireIssued(tagged,'Metric');return <div className="metric" data-status={t.status} data-claim><p className="metric__figure"><data value={t.value} data-status={t.status}>{fmt(t.value,t.precision??0)}</data><span className="mono">{t.unit}</span></p><p className="metric__label">{t.label}</p><Tag status={t.status}/></div>}
export function Metrics(){return <div className="metric-row"><Metric tagged={metric('cfar-a','detected')}/><Metric tagged={metric('cfar-a','maxAbsRangeError')}/><Metric tagged={metric('cfar-a','maxAbsVelocityError')}/></div>}
export function ResultTable(){const ds=dataset('cfar-a');return <div className="result-table" data-claim><table><caption><strong>{ds.title}</strong><span>{ds.scenario}</span></caption><thead><tr>{ds.columns.map(c=><th key={c.key} scope="col">{columnLabel(c)}</th>)}</tr></thead><tbody>{ds.rows.map((r,i)=><tr key={i}>{ds.columns.map(c=><td key={c.key} data-label={columnLabel(c)}>{c.unit===null?r[c.key]:(()=>{const t=requireIssued(cell(ds.id,i,c.key),'ResultTable');return <data value={t.value} data-status={t.status}>{fmt(t.value,t.precision??0)}</data>})()}</td>)}</tr>)}</tbody></table><p className="source"><Tag status={ds.status}/><a href={REPO.blob(ds.source.path)}>{ds.source.path}</a></p></div>}
export function Figure({id,table=false}:{id:FigureId;table?:boolean}){const f=FIGURES[id];return <figure className="figure" data-claim><a className="plate" href={mediaUrl(`${id}-1920.webp`)} data-figure-title={f.title} aria-label={`Open full figure: ${f.title}`}><img src={mediaUrl(`${id}-1280.webp`)} srcSet={[640,1280,1920].map(width=>`${mediaUrl(`${id}-${width}.webp`)} ${width}w`).join(', ')} sizes="(min-width:1280px) 900px, 100vw" width={sizes[id].width} height={sizes[id].height} alt={f.alt} loading="lazy" decoding="async"/><span className="plate-action"><Symbol kind="plus"/>Inspect figure</span></a><figcaption><p className="figure__title">{f.title}</p><p className="source"><Tag status={f.status}/><a href={REPO.blob(f.path)}>{f.path}</a></p></figcaption>{table&&<details className="disclosure"><summary>View as table</summary><ResultTable/></details>}</figure>}
export function Pending({title,children}:{title:string;children:ReactNode}){return <div className="pending"><span className="pending-mark"><Symbol kind="plus"/></span><h3>{title}</h3><p>{children}</p><Tag status="PLANNED"/></div>}
